import React from 'react';

export const Terms: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-16">
      <h1 className="text-4xl md:text-5xl font-extrabold mb-2 tracking-tight">Terms of Service</h1>
      <p className="text-sm text-drip-textTertiary mb-12">Last Updated: April 20, 2026</p>

      <div className="space-y-10 text-drip-textSecondary leading-relaxed">
        <Section title="Agreement to Terms">
          <p>
            By downloading, accessing, or using the Dripsta mobile application ("App") operated by
            Ryon Labs LLC ("Company", "we", "us"), you agree to these Terms of Service ("Terms").
            If you do not agree, do not use the App.
          </p>
        </Section>

        <Section title="Eligibility">
          <p>
            You must be at least 16 years old to use Dripsta. By using the App, you represent that
            you meet this age requirement.
          </p>
        </Section>

        <Section title="Account Registration">
          <ul className="list-disc pl-6 space-y-2">
            <li>You must provide accurate information when creating an account</li>
            <li>You are responsible for maintaining the security of your account</li>
            <li>You are responsible for all activity under your account</li>
            <li>
              One account per person. Creating multiple accounts to abuse the referral or credit
              system is prohibited
            </li>
          </ul>
        </Section>

        <Section title="The Service">
          <p>
            Dripsta provides AI-powered outfit analysis and scoring for entertainment and
            informational purposes. The AI feedback represents algorithmic assessment and should
            not be considered professional styling advice.
          </p>
        </Section>

        <Section title="User Content">
          <ul className="list-disc pl-6 space-y-2">
            <li>You retain ownership of photos you upload</li>
            <li>
              By making content "public" (Go Public), you grant Dripsta a non-exclusive, worldwide,
              royalty-free license to display your content within the App (Discover feed,
              leaderboard, profiles)
            </li>
            <li>You may remove your content from public visibility at any time via your profile</li>
            <li>You represent that you have the right to upload any content you submit</li>
            <li>
              You must not upload content that is illegal, offensive, sexually explicit, or
              violates others' rights
            </li>
          </ul>
        </Section>

        <Section title="AI Analysis Disclaimer">
          <ul className="list-disc pl-6 space-y-2">
            <li>
              AI scores and feedback are generated by artificial intelligence and are provided for
              entertainment and informational purposes only
            </li>
            <li>Scores are not a reflection of personal worth, attractiveness, or value</li>
            <li>
              The AI evaluates clothing and styling choices only — it does not and will not comment
              on body shape, size, or physical features
            </li>
            <li>AI analysis may contain errors or inconsistencies</li>
            <li>
              We do not guarantee the accuracy, completeness, or usefulness of AI-generated feedback
            </li>
          </ul>
        </Section>

        <Section title="Credits and Subscriptions">
          <ul className="list-disc pl-6 space-y-2">
            <li>New users receive 1 free credit</li>
            <li>Each outfit analysis consumes 1 credit</li>
            <li>
              Credits earned through referrals are granted when the invited user completes
              registration
            </li>
            <li>Referral credits (3 per invite) have no cap</li>
            <li>
              Credits have no monetary value and cannot be exchanged, transferred, or refunded
            </li>
            <li>Premium subscriptions are billed through Apple App Store or Google Play Store</li>
            <li>
              Subscription management and cancellation is handled through your device's app store
            </li>
            <li>
              We reserve the right to modify credit amounts, pricing, and subscription features
            </li>
          </ul>
        </Section>

        <Section title="Prohibited Conduct">
          <p>You agree not to:</p>
          <ul className="list-disc pl-6 space-y-2 mt-4">
            <li>Upload photos of other people without their consent</li>
            <li>Upload fraudulent, misleading, or AI-generated outfit photos</li>
            <li>Create fake accounts to abuse the referral system</li>
            <li>Manipulate the leaderboard through artificial means</li>
            <li>Harass, bully, or engage in toxic behavior toward other users</li>
            <li>Use the App for any illegal purpose</li>
            <li>Reverse engineer, copy, or modify the App</li>
            <li>Use automated systems or bots to interact with the App</li>
          </ul>
        </Section>

        <Section title="Reporting and Moderation">
          <ul className="list-disc pl-6 space-y-2">
            <li>Users can report content using the "Report" button</li>
            <li>
              We review reported content and may remove it or suspend accounts at our discretion
            </li>
            <li>Repeated violations may result in permanent account termination</li>
          </ul>
        </Section>

        <Section title="Intellectual Property">
          <ul className="list-disc pl-6 space-y-2">
            <li>
              Dripsta, its logo, design, and AI scoring system are the property of Ryon Labs LLC
            </li>
            <li>You may not use our branding, name, or content without written permission</li>
            <li>
              Share cards generated by the App may be shared on social media with Dripsta branding
              intact
            </li>
          </ul>
        </Section>

        <Section title="Limitation of Liability">
          <p>To the maximum extent permitted by law:</p>
          <ul className="list-disc pl-6 space-y-2 mt-4">
            <li>
              Ryon Labs LLC has no obligation to compensate users for any damages arising from the
              use of the App
            </li>
            <li>Our total aggregate liability shall not exceed $100 USD</li>
            <li>
              We are not responsible for any third-party AI provider errors, outages, or
              inaccuracies
            </li>
            <li>We are not responsible for decisions made based on AI feedback</li>
            <li>We are not liable for any emotional distress related to AI scores or feedback</li>
          </ul>
        </Section>

        <Section title="Assumption of Risk">
          <p>By using the App, you acknowledge that:</p>
          <ul className="list-disc pl-6 space-y-2 mt-4">
            <li>AI-generated scores are subjective algorithmic assessments</li>
            <li>
              Public participation (leaderboard, Discover) exposes your content to other users'
              reactions
            </li>
            <li>
              Fashion scoring is inherently subjective and may not align with your personal
              assessment
            </li>
          </ul>
        </Section>

        <Section title="Indemnification">
          <p>
            You agree to indemnify and hold harmless Ryon Labs LLC from any claims, damages, or
            expenses arising from your use of the App or violation of these Terms.
          </p>
        </Section>

        <Section title="Termination">
          <ul className="list-disc pl-6 space-y-2">
            <li>You may delete your account at any time</li>
            <li>We may suspend or terminate your account for violation of these Terms</li>
            <li>Upon termination, your right to use the App ceases immediately</li>
          </ul>
        </Section>

        <Section title="Governing Law">
          <p>
            These Terms are governed by the laws of the State of Delaware, USA, without regard to
            conflict of law principles.
          </p>
        </Section>

        <Section title="Dispute Resolution">
          <p>
            Any disputes shall be resolved through binding arbitration in accordance with the rules
            of the American Arbitration Association. You waive any right to participate in class
            action lawsuits.
          </p>
        </Section>

        <Section title="Force Majeure">
          <p>
            We are not liable for failure to perform due to circumstances beyond our reasonable
            control, including but not limited to natural disasters, war, terrorism, pandemics,
            government actions, or third-party service failures.
          </p>
        </Section>

        <Section title="Reservation of Rights">
          <p>
            We reserve the right to modify, suspend, or discontinue any aspect of the App at any
            time without notice. We reserve the right to modify these Terms at any time.
          </p>
        </Section>

        <Section title="Severability">
          <p>
            If any provision of these Terms is found unenforceable, the remaining provisions
            continue in full effect.
          </p>
        </Section>

        <Section title="Contact">
          <p>For questions about these Terms:</p>
          <ul className="list-none space-y-1 mt-4">
            <li>
              Email:{' '}
              <a href="mailto:info@ryonlabs.com" className="text-drip-primary underline">
                info@ryonlabs.com
              </a>
            </li>
            <li>Company: Ryon Labs LLC</li>
          </ul>
        </Section>
      </div>
    </div>
  );
};

const Section: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => (
  <section>
    <h2 className="text-2xl font-bold text-drip-text mb-4">{title}</h2>
    {children}
  </section>
);
